### ISSUE TITLE
Interrupted PathfinderRequest never finishes

### ISSUE THREAD

**Issue by DaanVanYperen** [libgdx/gdx-ai#23]
On snapshot, `PathfinderRequest#statusChanged` is set to `true` by `PathfinderRequest#changeStatus` but never reset. 

This causes each call to `IndexedAStarPathFinder#search(request, timeToRun)` to restart the search, so a route that takes longer to calculate than timeToRun will never finish 

Working around it for now by setting stateChanged by hand after the first search, but assume this is something the finder is supposed to do.

```java
request = new PathFinderRequest<>(..);
request.changeStatus(PathFinderRequest.SEARCH_INITIALIZED);
```

```java
finder.search(request, TimeUtils.millisToNanos(25))
```

**Comment by davebaol** [comment]
Yes, you're right.
I have some "old" uncommitted changes that should fix this issue. I'll push them in a few hours.
Thanks :smile:

**Comment by DaanVanYperen** [comment]
Awesome! Thanks. 

Using the interruptable pathfinding for https://github.com/DaanVanYperen/ns2-scc-profiler to keep the framerate up under GWT, it's working great so far.

**Comment by davebaol** [comment]
Ok I've isolated my local changes and pushed only stuff related to pathfinding in order to fix this issue and add a hierarchical test. It should work properly now. Let me know if you have problems.
The remaining uncommitted changes will be pushed soon, I just need some time to clean up the code.
Later I'll release gdx-ai 1.5.0.

PS:
Out of curiosity, I've just tried the online version of your application, but can't understand the meaning of the icons. Anyways I've starred your repo 'cause I'm glad you're using gdx-ai :wink:
